# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      payload:
        patterns:
          - "payload"
          - "@payloadcms/*"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/eslint-plugin-next"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      turbo:
        patterns:
          - "turbo"
          - "eslint-config-turbo"
      lint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
        exclude-patterns:
          - "eslint-config-next"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      patches:
        update-types:
          - "patch"
