# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      lint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
        exclude-patterns:
          - "eslint-config-next"
