version: "3"

services:
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    expose:
      - 27017

  cms:
    build:
      context: .
      args:
        - PROJECT=cms
        - GIT_COMMIT_SHA=test
    depends_on:
      - mongo
    env_file:
      - .env.docker-compose.prod
    expose:
      - 3001

  web:
    build:
      context: .
      args:
        - PROJECT=web
        - GIT_COMMIT_SHA=test
    depends_on:
      - cms
    env_file:
      - .env.docker-compose.prod
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  data:
