packages:
  - apps/*
  - packages/*
catalog:
  "@tailwindcss/typography": ^0.5.12
  "@types/node": ^20.14.11
  "@types/react-dom": ^18.3.0
  "@types/react": ^18.3.3
  autoprefixer: ^10.4.19
  clsx: ^2.1.1
  eslint: ^8.57.0
  postcss: ^8.4.38
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwind-merge: ^2.4.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.6
  typescript: ^5.5.4
