packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.39.4
  "@tailwindcss/postcss": ^4.2.2
  "@tailwindcss/typography": ^0.5.19
  "@types/node": ^24.12.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/eslint-plugin": ^8.58.0
  "@typescript-eslint/parser": ^8.58.0
  "@typescript-eslint/utils": ^8.58.0
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.39.4
  postcss: ^8.5.8
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  tailwindcss-animate: ^1.0.7
  next: ^16.2.2
  "@next/eslint-plugin-next": ^16.2.2
  typescript: ~5.9.3
  typescript-eslint: ^8.58.0

# https://pnpm.io/supply-chain-security
minimumReleaseAge: 1440
