packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": "^9.23.0"
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^22.13.13
  "@typescript-eslint/eslint-plugin": ^8.28.0
  "@typescript-eslint/parser": ^8.28.0
  "@typescript-eslint/utils": ^8.28.0
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.23.0
  postcss: ^8.5.3
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  typescript-eslint: ^8.28.0
catalogs:
  react18:
    "@types/react-dom": ^18.3.5
    "@types/react": ^18.3.16
    react-dom: ^18.3.1
    react: ^18.3.1
  react19:
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.1
    react-dom: ^19.0.0
    react: ^19.0.0
