packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.39.2
  "@tailwindcss/postcss": ^4.1.18
  "@tailwindcss/typography": ^0.5.19
  "@types/node": ^24.10.9
  "@types/react": ^19.2.9
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/eslint-plugin": ^8.53.1
  "@typescript-eslint/parser": ^8.53.1
  "@typescript-eslint/utils": ^8.53.1
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.39.2
  postcss: ^8.5.6
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  typescript: ^5.9.3
  typescript-eslint: ^8.56.0

# https://pnpm.io/supply-chain-security
minimumReleaseAge: 1440
