packages:
  - apps/*
  - packages/*
  - tests
catalog:
  "@playwright/test": ^1.48.0
  "@tailwindcss/typography": ^0.5.15
  "@types/node": ^22.7.5
  "@types/react-dom": ^18.3.0
  "@types/react": ^18.3.11
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  eslint: ^8.57.1
  postcss: ^8.4.47
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwind-merge: ^2.5.3
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.13
  typescript: ^5.6.3
