packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": "^9.20.0"
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^22.13.2
  "@typescript-eslint/eslint-plugin": ^8.24.0
  "@typescript-eslint/parser": ^8.24.0
  "@typescript-eslint/utils": ^8.24.0
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  eslint: ^9.20.1
  postcss: ^8.5.2
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
catalogs:
  react18:
    "@types/react-dom": ^18.3.5
    "@types/react": ^18.3.16
    react-dom: ^18.3.1
    react: ^18.3.1
  react19:
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.1
    react-dom: ^19.0.0
    react: ^19.0.0
