packages:
  - apps/*
  - packages/*
  - tests

catalog:
  "@eslint/js": ^9.33.0
  "@playwright/test": "^1.54.2"
  "@tailwindcss/postcss": ^4.1.12
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^24.2.1
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7
  "@typescript-eslint/eslint-plugin": ^8.39.1
  "@typescript-eslint/parser": ^8.39.1
  "@typescript-eslint/utils": ^8.39.1
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.33.0
  postcss: ^8.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tailwindcss-animate: ^1.0.7
  typescript: ^5.9.2
  typescript-eslint: ^8.39.1
