packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.35.0
  '@tailwindcss/postcss': ^4.1.13
  '@tailwindcss/typography': ^0.5.18
  '@types/node': ^24.4.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@typescript-eslint/eslint-plugin': ^8.43.0
  '@typescript-eslint/parser': ^8.43.0
  '@typescript-eslint/utils': ^8.43.0
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.35.0
  postcss: ^8.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tailwindcss-animate: ^1.0.7
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
