packages:
  - apps/*
  - packages/*
catalog:
  "@tailwindcss/typography": ^0.5.14
  "@types/node": ^22.5.0
  "@types/react-dom": ^18.3.0
  "@types/react": ^18.3.4
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  eslint: ^8.57.0
  postcss: ^8.4.40
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwind-merge: ^2.5.2
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
