packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": "^9.13.0"
  "@tailwindcss/typography": ^0.5.15
  "@types/node": ^22.8.4
  "@types/react-dom": ^18.3.1
  "@types/react": ^18.3.12
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  eslint: ^9.13.0
  postcss: ^8.4.47
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwind-merge: ^2.5.4
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  typescript-eslint: ^8.12.2
