packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.30.1
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^24.0.13
  "@types/react-dom": ^19.0.1
  "@types/react": ^19.0.1
  "@typescript-eslint/eslint-plugin": ^8.35.1
  "@typescript-eslint/parser": ^8.35.1
  "@typescript-eslint/utils": ^8.35.1
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  eslint: ^9.30.1
  postcss: ^8.5.6
  react-dom: ^19.1.0
  react: ^19.1.0
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.17
  typescript-eslint: ^8.35.1
  typescript: ^5.8.3
