// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "errors": {
    "ilmomasiina-event-not-found": "Event not found. Please check the URL.",
    "ilmomasiina-fetch-fail": "Failed to fetch events from Ilmomasiina. Please try again later.",
    "ilmomasiina-ilmo-missing-quota-id": "Invalid request. Please try again.",
    "ilmomasiina-signup-not-found": "Sign up not found. Please check the URL.",
    "ilmomasiina-unknown-error": "An unknown error occurred. Please try again later.",
    "ilmomasiina-validation-failed": "Validation failed. Please check the form.",
    "ilmo": {
      "code": {
        "BadSession": "Session has expired. Please log in again.",
        "EditConflict": "Edit conflict. Please try again.",
        "WouldMoveSignupsToQueue": "Signups would be moved to the queue.",
        "WrongOldPassword": "Incorrect old password.",
        "SignupsClosed": "Signups are closed.",
        "NoSuchQuota": "Quota not found.",
        "NoSuchSignup": "Signup not found.",
        "BadEditToken": "Invalid edit token.",
        "CannotDeleteSelf": "You cannot delete yourself.",
        "InitialSetupNeeded": "Initial setup needed.",
        "InitialSetupAlreadyDone": "Initial setup already done.",
        "SignupValidationError": "Signup validation failed.",
        "EventValidationError": "Event validation failed.",
        "FST_ERR_VALIDATION": "Validation failed."
      },
      "fieldError": {
        "missing": "This field is required.",
        "wrongType": "Invalid type.",
        "tooLong": "Value is too long.",
        "invalidEmail": "Invalid email address.",
        "notANumber": "Value must be a number.",
        "notAnOption": "Invalid option."
      }
    }
  }
};
export default messages;