/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type LinkRowBlockLink =
  | {
      icon:
        | 'AtSign'
        | 'Banknote'
        | 'BookMarked'
        | 'ChevronDown'
        | 'ChevronUp'
        | 'ChevronsUpDown'
        | 'Circle'
        | 'Clock'
        | 'ExternalLink'
        | 'File'
        | 'Facebook'
        | 'Github'
        | 'HelpCircle'
        | 'Image'
        | 'Inbox'
        | 'Instagram'
        | 'Languages'
        | 'Linkedin'
        | 'MapPin'
        | 'Menu'
        | 'Telegram'
        | 'TikLogo'
        | 'Tiktok'
        | 'X';
      label: string;
      linkType?: ('external' | 'internal') | null;
      url?: string | null;
      page?: (number | null) | Page;
      id?: string | null;
    }[]
  | null;
export type MainNavigationItem = {
  type?: ('page' | 'topic') | null;
  pageConfig?: {
    page: number | Page;
  };
  topicConfig?: MainNavigationTopicConfig;
  id?: string | null;
}[];

export interface Config {
  collections: {
    users: User;
    pages: Page;
    media: Media;
    topics: Topic;
    'board-members': BoardMember;
    boards: Board;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    footer: Footer;
    'landing-page': LandingPage;
    'main-navigation': MainNavigation;
  };
}
export interface User {
  id: number;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Page {
  id: number;
  title: string;
  description: string;
  content: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  };
  path?: string | null;
  topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  slug: string;
  hidden: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface Topic {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface BoardMember {
  id: number;
  guildYear:
    | '2024'
    | '2023'
    | '2022'
    | '2021'
    | '2020'
    | '2019'
    | '2018'
    | '2017'
    | '2016'
    | '2015'
    | '2014'
    | '2013'
    | '2012'
    | '2011'
    | '2010'
    | '2009'
    | '2008'
    | '2007'
    | '2006'
    | '2005'
    | '2004'
    | '2003'
    | '2002'
    | '2001'
    | '2000'
    | '1999'
    | '1998'
    | '1997'
    | '1996'
    | '1995'
    | '1994'
    | '1993'
    | '1992'
    | '1991'
    | '1990'
    | '1989'
    | '1988'
    | '1987'
    | '1986';
  photo?: (number | null) | Media;
  name: string;
  title: string;
  email: string;
  telegram: string;
  updatedAt: string;
  createdAt: string;
}
export interface Board {
  id: number;
  year:
    | '2024'
    | '2023'
    | '2022'
    | '2021'
    | '2020'
    | '2019'
    | '2018'
    | '2017'
    | '2016'
    | '2015'
    | '2014'
    | '2013'
    | '2012'
    | '2011'
    | '2010'
    | '2009'
    | '2008'
    | '2007'
    | '2006'
    | '2005'
    | '2004'
    | '2003'
    | '2002'
    | '2001'
    | '2000'
    | '1999'
    | '1998'
    | '1997'
    | '1996'
    | '1995'
    | '1994'
    | '1993'
    | '1992'
    | '1991'
    | '1990'
    | '1989'
    | '1988'
    | '1987'
    | '1986';
  description: string;
  groupPhoto?: (number | null) | Media;
  boardMembers: {
    boardMember?: (number | null) | BoardMember;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Footer {
  id: number;
  layout: (LinkRowBlock | SponsorLogoRowBlock)[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface LinkRowBlock {
  showLabel: boolean;
  links?: LinkRowBlockLink;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link-row';
}
export interface SponsorLogoRowBlock {
  logos?:
    | {
        image: number | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logo-row';
}
export interface LandingPage {
  id: number;
  heroText: string;
  heroImages: {
    image?: (number | null) | Media;
    id?: string | null;
  }[];
  body: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface MainNavigation {
  id: number;
  items: MainNavigationItem;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface MainNavigationTopicConfig {
  topic: number | Topic;
  categories?:
    | {
        title: string;
        pages?:
          | {
              page: number | Page;
              id?: string | null;
            }[]
          | null;
        externalLinks?:
          | {
              title: string;
              href: string;
              icon:
                | 'AtSign'
                | 'Banknote'
                | 'BookMarked'
                | 'ChevronDown'
                | 'ChevronUp'
                | 'ChevronsUpDown'
                | 'Circle'
                | 'Clock'
                | 'ExternalLink'
                | 'File'
                | 'Facebook'
                | 'Github'
                | 'HelpCircle'
                | 'Image'
                | 'Inbox'
                | 'Instagram'
                | 'Languages'
                | 'Linkedin'
                | 'MapPin'
                | 'Menu'
                | 'Telegram'
                | 'TikLogo'
                | 'Tiktok'
                | 'X';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
}
